spring:
  application:
    name: jw-gateway
server:
  port: 10010
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
zuul:
  retryable: true
  routes:
    user-service: /user/**
    auth-service: /auth/**
    manager-service: /manager/**
    upload-service: /upload/**
    login-service:
      path: /*
      url: http://localhost:8081
  add-host-header: true
  sensitive-headers:
ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数j
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms
ly:
  jwt:
    pubKeyPath: C:/Users/zxw/Desktop/key/rsa.pub
    cookieName: LY_TOKEN
  filter:
    allowPaths:
      - /auth
      - /login