server:
  port: 8086
spring:
  application:
    name: sms-service
  redis:
    host: localhost
  rabbitmq:
    host: localhost
    username: leyou
    password: leyou
    virtual-host: /leyou
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 210000ms
        multiplier: 2
    publisher-confirms: true
jw:
  sms:
    accessKeyId: JWffwFJIwada # 你自己的accessKeyId
    accessKeySecret: aySRliswq8fe7rF9gQyy1Izz4MQ # 你自己的AccessKeySecret
    signName: 教务管理系统 # 签名名称
    verifyCodeTemplate: SMS_123456 # 模板名称