server:
  port: 8081
spring:
  application:
    name: user-service
  thymeleaf:
    cache: false
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/new?userSSL=false&&characterEncoding=utf8
  jpa:
    hibernate:
      #     更新或者创建数据表结构
      ddl-auto: update
    show-sql: true
  redis:
    host: localhost
  rabbitmq:
    virtual-host: /leyou
    username: leyou
    password: leyou
    host: localhost
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    ip-address: 127.0.0.7
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
